package eu.europa.ec.fisheries.wsdl.source;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.6 2015-03-16T16:01:40.213+01:00
 * Generated source version: 2.7.6
 *
 */
@WebServiceClient(name = "DataSourceQueueService",
        wsdlLocation = "file:/C:/Projekt/unionvms/branches/dev/unionvms-maven/archetypes/unionvms-exchange-archetype/model/src/main/resources/contract/DataSourceService.wsdl",
        targetNamespace = "source.wsdl.fisheries.ec.europa.eu")
public class DataSourceQueueService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("source.wsdl.fisheries.ec.europa.eu", "DataSourceQueueService");
    public final static QName DataSourcePortType = new QName("source.wsdl.fisheries.ec.europa.eu", "DataSourcePortType");

    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Projekt/unionvms/branches/dev/unionvms-maven/archetypes/unionvms-exchange-archetype/model/src/main/resources/contract/DataSourceService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(DataSourceQueueService.class.getName())
                    .log(java.util.logging.Level.INFO,
                            "Can not initialize the default wsdl from {0}", "file:/C:/Projekt/unionvms/branches/dev/unionvms-maven/archetypes/unionvms-exchange-archetype/model/src/main/resources/contract/DataSourceService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public DataSourceQueueService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DataSourceQueueService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DataSourceQueueService() {
        super(WSDL_LOCATION, SERVICE);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public DataSourceQueueService(WebServiceFeature... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public DataSourceQueueService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public DataSourceQueueService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return returns DataSourcePortType
     */
    @WebEndpoint(name = "DataSourcePortType")
    public DataSourcePortType getDataSourcePortType() {
        return super.getPort(DataSourcePortType, DataSourcePortType.class);
    }

    /**
     *
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to
     * configure on the proxy. Supported features not in the
     * <code>features</code> parameter will have their default values.
     * @return returns DataSourcePortType
     */
    @WebEndpoint(name = "DataSourcePortType")
    public DataSourcePortType getDataSourcePortType(WebServiceFeature... features) {
        return super.getPort(DataSourcePortType, DataSourcePortType.class, features);
    }

}
