package eu.europa.ec.fisheries.wsdl.source;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.6 2015-03-16T16:01:40.212+01:00
 * Generated source version: 2.7.6
 *
 */
@WebService(targetNamespace = "source.wsdl.fisheries.ec.europa.eu", name = "DataSourcePortType")
@XmlSeeAlso({ObjectFactory.class, eu.europa.ec.fisheries.wsdl.types.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface DataSourcePortType {

    @WebResult(name = "GetDataResponse", targetNamespace = "source.wsdl.fisheries.ec.europa.eu", partName = "body")
    @WebMethod(operationName = "GetModuleObject")
    public GetDataResponse getModuleObject(
            @WebParam(partName = "body", name = "GetDataRequest", targetNamespace = "source.wsdl.fisheries.ec.europa.eu") GetDataRequest body
    ) throws Exception;
}
