package eu.europa.ec.fisheries.wsdl.source;

import javax.xml.ws.WebFault;

/**
 * This class was generated by Apache CXF 2.7.6 2015-03-16T16:01:40.202+01:00
 * Generated source version: 2.7.6
 */
@WebFault(name = "ModuleObjectException", targetNamespace = "types.wsdl.fisheries.ec.europa.eu")
public class Exception extends java.lang.Exception {

    private eu.europa.ec.fisheries.wsdl.types.ModuleObjectException moduleObjectException;

    public Exception() {
        super();
    }

    public Exception(String message) {
        super(message);
    }

    public Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public Exception(String message, eu.europa.ec.fisheries.wsdl.types.ModuleObjectException moduleObjectException) {
        super(message);
        this.moduleObjectException = moduleObjectException;
    }

    public Exception(String message, eu.europa.ec.fisheries.wsdl.types.ModuleObjectException moduleObjectException, Throwable cause) {
        super(message, cause);
        this.moduleObjectException = moduleObjectException;
    }

    public eu.europa.ec.fisheries.wsdl.types.ModuleObjectException getFaultInfo() {
        return this.moduleObjectException;
    }
}
