package eu.europa.ec.fisheries.schema.exchange.source.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2015-08-28T14:54:54.096+02:00
 * Generated source version: 2.7.6
 * 
 */
@WebService(targetNamespace = "urn:source.exchange.schema.fisheries.ec.europa.eu:v1", name = "ExchangeDataSourcePortType")
@XmlSeeAlso({eu.europa.ec.fisheries.schema.exchange.v1.ObjectFactory.class, ObjectFactory.class, eu.europa.ec.fisheries.schema.exchange.common.v1.ObjectFactory.class, eu.europa.ec.fisheries.schema.exchange.service.v1.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ExchangeDataSourcePortType {

    @WebResult(name = "UnregisterServiceResponse", targetNamespace = "urn:source.exchange.schema.fisheries.ec.europa.eu:v1", partName = "body")
    @WebMethod(operationName = "UnregisterService")
    public UnregisterServiceResponse unregisterService(
        @WebParam(partName = "body", name = "UnregisterServiceRequest", targetNamespace = "urn:source.exchange.schema.fisheries.ec.europa.eu:v1")
        UnregisterServiceRequest body
    ) throws ExchangeFault;

    @WebResult(name = "CreateLogResponse", targetNamespace = "urn:source.exchange.schema.fisheries.ec.europa.eu:v1", partName = "body")
    @WebMethod(operationName = "CreateLog")
    public CreateLogResponse createLog(
        @WebParam(partName = "body", name = "CreateLogRequest", targetNamespace = "urn:source.exchange.schema.fisheries.ec.europa.eu:v1")
        CreateLogRequest body
    ) throws ExchangeFault;

    @WebResult(name = "GetLogListByQueryResponse", targetNamespace = "urn:source.exchange.schema.fisheries.ec.europa.eu:v1", partName = "body")
    @WebMethod(operationName = "GetLogListByQuery")
    public GetLogListByQueryResponse getLogListByQuery(
        @WebParam(partName = "body", name = "GetLogListByQueryRequest", targetNamespace = "urn:source.exchange.schema.fisheries.ec.europa.eu:v1")
        GetLogListByQueryRequest body
    ) throws ExchangeFault;

    @WebResult(name = "GetServiceSettingsResponse", targetNamespace = "urn:source.exchange.schema.fisheries.ec.europa.eu:v1", partName = "body")
    @WebMethod(operationName = "GetServiceSettings")
    public GetServiceSettingsResponse getServiceSettings(
        @WebParam(partName = "body", name = "GetServiceSettingsRequest", targetNamespace = "urn:source.exchange.schema.fisheries.ec.europa.eu:v1")
        GetServiceSettingsRequest body
    ) throws ExchangeFault;

    @WebResult(name = "GetServiceCapabilitiesResponse", targetNamespace = "urn:source.exchange.schema.fisheries.ec.europa.eu:v1", partName = "body")
    @WebMethod(operationName = "GetServiceCapabilities")
    public GetServiceCapabilitiesResponse getServiceCapabilities(
        @WebParam(partName = "body", name = "GetServiceCapabilitiesRequest", targetNamespace = "urn:source.exchange.schema.fisheries.ec.europa.eu:v1")
        GetServiceCapabilitiesRequest body
    ) throws ExchangeFault;

    @WebResult(name = "GetServiceResponse", targetNamespace = "urn:source.exchange.schema.fisheries.ec.europa.eu:v1", partName = "body")
    @WebMethod(operationName = "GetService")
    public GetServiceResponse getService(
        @WebParam(partName = "body", name = "GetServiceRequest", targetNamespace = "urn:source.exchange.schema.fisheries.ec.europa.eu:v1")
        GetServiceRequest body
    ) throws ExchangeFault;

    @WebResult(name = "GetServiceListResponse", targetNamespace = "urn:source.exchange.schema.fisheries.ec.europa.eu:v1", partName = "body")
    @WebMethod(operationName = "GetServiceList")
    public GetServiceListResponse getServiceList(
        @WebParam(partName = "body", name = "GetServiceListRequest", targetNamespace = "urn:source.exchange.schema.fisheries.ec.europa.eu:v1")
        GetServiceListRequest body
    ) throws ExchangeFault;

    @WebResult(name = "RegisterServiceResponse", targetNamespace = "urn:source.exchange.schema.fisheries.ec.europa.eu:v1", partName = "body")
    @WebMethod(operationName = "RegisterService")
    public RegisterServiceResponse registerService(
        @WebParam(partName = "body", name = "RegisterServiceRequest", targetNamespace = "urn:source.exchange.schema.fisheries.ec.europa.eu:v1")
        RegisterServiceRequest body
    ) throws ExchangeFault;
}
