
package eu.europa.ec.fisheries.schema.exchange.module.v1;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.6
 * 2015-08-13T16:42:38.793+02:00
 * Generated source version: 2.7.6
 */

@WebFault(name = "exceptionType", targetNamespace = "urn:common.exchange.schema.fisheries.ec.europa.eu:v1")
public class ExchangeException extends Exception {
    
    private eu.europa.ec.fisheries.schema.exchange.common.v1.ExceptionType exceptionType;

    public ExchangeException() {
        super();
    }
    
    public ExchangeException(String message) {
        super(message);
    }
    
    public ExchangeException(String message, Throwable cause) {
        super(message, cause);
    }

    public ExchangeException(String message, eu.europa.ec.fisheries.schema.exchange.common.v1.ExceptionType exceptionType) {
        super(message);
        this.exceptionType = exceptionType;
    }

    public ExchangeException(String message, eu.europa.ec.fisheries.schema.exchange.common.v1.ExceptionType exceptionType, Throwable cause) {
        super(message, cause);
        this.exceptionType = exceptionType;
    }

    public eu.europa.ec.fisheries.schema.exchange.common.v1.ExceptionType getFaultInfo() {
        return this.exceptionType;
    }
}
