package eu.europa.ec.fisheries.schema.exchange.module.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2015-08-28T14:54:53.391+02:00
 * Generated source version: 2.7.6
 * 
 */
@WebService(targetNamespace = "urn:module.exchange.schema.fisheries.ec.europa.eu:v1", name = "ExchangeModulePortType")
@XmlSeeAlso({eu.europa.ec.fisheries.schema.exchange.v1.ObjectFactory.class, ObjectFactory.class, eu.europa.ec.fisheries.schema.exchange.common.v1.ObjectFactory.class, eu.europa.ec.fisheries.schema.exchange.service.v1.ObjectFactory.class, eu.europa.ec.fisheries.schema.exchange.poll.v1.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ExchangeModulePortType {

    @WebResult(name = "UnregisterServiceResponse", targetNamespace = "urn:module.exchange.schema.fisheries.ec.europa.eu:v1", partName = "body")
    @WebMethod(operationName = "UnregisterService")
    public UnregisterServiceResponse unregisterService(
        @WebParam(partName = "body", name = "UnregisterServiceRequest", targetNamespace = "urn:module.exchange.schema.fisheries.ec.europa.eu:v1")
        UnregisterServiceRequest body
    ) throws ExchangeFault;

    @WebResult(name = "GetServiceListResponse", targetNamespace = "urn:module.exchange.schema.fisheries.ec.europa.eu:v1", partName = "body")
    @WebMethod(operationName = "GetServiceList")
    public GetServiceListResponse getServiceList(
        @WebParam(partName = "body", name = "GetServiceListRequest", targetNamespace = "urn:module.exchange.schema.fisheries.ec.europa.eu:v1")
        GetServiceListRequest body
    ) throws ExchangeFault;

    @WebMethod(operationName = "CreatePoll")
    public void createPoll(
        @WebParam(partName = "body", mode = WebParam.Mode.INOUT, name = "CreatePollResponse", targetNamespace = "urn:module.exchange.schema.fisheries.ec.europa.eu:v1")
        javax.xml.ws.Holder<CreatePollResponse> body
    ) throws ExchangeException;

    @WebResult(name = "RegisterServiceResponse", targetNamespace = "urn:module.exchange.schema.fisheries.ec.europa.eu:v1", partName = "body")
    @WebMethod(operationName = "RegisterService")
    public RegisterServiceResponse registerService(
        @WebParam(partName = "body", name = "RegisterServiceRequest", targetNamespace = "urn:module.exchange.schema.fisheries.ec.europa.eu:v1")
        RegisterServiceRequest body
    ) throws ExchangeFault;

    @WebResult(name = "GetServiceSettingsResponse", targetNamespace = "urn:module.exchange.schema.fisheries.ec.europa.eu:v1", partName = "body")
    @WebMethod(operationName = "GetServiceSettings")
    public GetServiceSettingsResponse getServiceSettings(
        @WebParam(partName = "body", name = "GetServiceSettingsRequest", targetNamespace = "urn:module.exchange.schema.fisheries.ec.europa.eu:v1")
        GetServiceSettingsRequest body
    ) throws ExchangeFault;

    @WebResult(name = "GetServiceCapabilitiesResponse", targetNamespace = "urn:module.exchange.schema.fisheries.ec.europa.eu:v1", partName = "body")
    @WebMethod(operationName = "GetServiceCapabilities")
    public GetServiceCapabilitiesResponse getServiceCapabilities(
        @WebParam(partName = "body", name = "GetServiceCapabilitiesRequest", targetNamespace = "urn:module.exchange.schema.fisheries.ec.europa.eu:v1")
        GetServiceCapabilitiesRequest body
    ) throws ExchangeFault;
}
