package eu.europa.ec.fisheries.schema.exchange.registry.v1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2016-03-22T18:31:38.298+01:00
 * Generated source version: 2.7.6
 * 
 */
@WebServiceClient(name = "ExchangeRegistryService", 
                  wsdlLocation = "file:/C:/projects/unionvms/UNIONVMS/branches/dev/Modules/Exchange/APP/model/src/main/resources/contract/ExchangeRegistryService.wsdl",
                  targetNamespace = "urn:registry.exchange.schema.fisheries.ec.europa.eu:v1") 
public class ExchangeRegistryService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:registry.exchange.schema.fisheries.ec.europa.eu:v1", "ExchangeRegistryService");
    public final static QName ExchangeRegistryServicePortType = new QName("urn:registry.exchange.schema.fisheries.ec.europa.eu:v1", "ExchangeRegistryServicePortType");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/projects/unionvms/UNIONVMS/branches/dev/Modules/Exchange/APP/model/src/main/resources/contract/ExchangeRegistryService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ExchangeRegistryService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/projects/unionvms/UNIONVMS/branches/dev/Modules/Exchange/APP/model/src/main/resources/contract/ExchangeRegistryService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ExchangeRegistryService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ExchangeRegistryService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ExchangeRegistryService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ExchangeRegistryService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ExchangeRegistryService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ExchangeRegistryService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ExchangeRegistryServicePortType
     */
    @WebEndpoint(name = "ExchangeRegistryServicePortType")
    public ExchangeRegistryServicePortType getExchangeRegistryServicePortType() {
        return super.getPort(ExchangeRegistryServicePortType, ExchangeRegistryServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ExchangeRegistryServicePortType
     */
    @WebEndpoint(name = "ExchangeRegistryServicePortType")
    public ExchangeRegistryServicePortType getExchangeRegistryServicePortType(WebServiceFeature... features) {
        return super.getPort(ExchangeRegistryServicePortType, ExchangeRegistryServicePortType.class, features);
    }

}
