
package eu.europa.ec.fisheries.schema.exchange.plugin.v1;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.6
 * 2016-03-22T18:31:38.920+01:00
 * Generated source version: 2.7.6
 */

@WebFault(name = "PluginFault", targetNamespace = "urn:types.plugin.exchange.schema.fisheries.ec.europa.eu:v1")
public class PluginFault extends Exception {
    
    private eu.europa.ec.fisheries.schema.exchange.plugin.types.v1.PluginFault pluginFault;

    public PluginFault() {
        super();
    }
    
    public PluginFault(String message) {
        super(message);
    }
    
    public PluginFault(String message, Throwable cause) {
        super(message, cause);
    }

    public PluginFault(String message, eu.europa.ec.fisheries.schema.exchange.plugin.types.v1.PluginFault pluginFault) {
        super(message);
        this.pluginFault = pluginFault;
    }

    public PluginFault(String message, eu.europa.ec.fisheries.schema.exchange.plugin.types.v1.PluginFault pluginFault, Throwable cause) {
        super(message, cause);
        this.pluginFault = pluginFault;
    }

    public eu.europa.ec.fisheries.schema.exchange.plugin.types.v1.PluginFault getFaultInfo() {
        return this.pluginFault;
    }
}
