package eu.europa.ec.fisheries.wsdl.module;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.6 2015-03-16T16:01:39.678+01:00
 * Generated source version: 2.7.6
 *
 */
@WebService(targetNamespace = "module.wsdl.fisheries.ec.europa.eu", name = "ModuleObjectModulePortType")
@XmlSeeAlso({eu.europa.ec.fisheries.wsdl.types.ObjectFactory.class, ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ModuleObjectModulePortType {

    @WebResult(name = "GetModuleObjectResponse", targetNamespace = "module.wsdl.fisheries.ec.europa.eu", partName = "body")
    @WebMethod(operationName = "GetModuleObject")
    public GetModuleObjectResponse getModuleObject(
            @WebParam(partName = "body", name = "GetModuleObjectRequest", targetNamespace = "module.wsdl.fisheries.ec.europa.eu") GetModuleObjectRequest body
    ) throws GetModuleObjectFaultException;
}
